export default {
  ADD: "add",
  CATEGORY: "categorySelected",
  CSS_COMPLETE: "css-complete",
  CSS_PROGRESS:"css-progress",
  CSS_LIFE:"css-life",
  DEFAULT: "default",
  END_TIME: "end-time",
  FAILED: "failed",
  HTML_COMPLETE: "html-complete",
  HTML_PROGRESS:"html-progress",
  HTML_LIFE:"html-life",
  JS_COMPLETE: "js-complete",
  JS_PROGRESS:"js-progress",
  JS_LIFE:"js-life",
  LIFE: 4,
  MINUTES: "minutes",
  PROGRESS: "progress",
  REMOVE: "remove",
  RESPONSE: "response",
  START_TIME: "start-time",
  SUCCESS: "success",
  TOTAL_RESPONSES: "total-responses",
  NOTIFICATION: {
    buttom: "Continuar",
    title: "Has Perdido, debes empezar de 0.",
    type: "default",
  },
  NOTIFICATION_FAILED: {
    buttom: "Continuar",
    title: "La respuesta es correcta es:",
    type: "failed",
  },
  NOTIFICATION_SUCCESS: {
    buttom: "Continuar",
    title: "¡Buen Trabajo!",
    type: "success",
  },
};
